In [210]:
from bs4 import BeautifulSoup
import requests 
import re
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder

In [211]:
# This function returnes the GTD_Data_Frame_Without_Duplicates as dataframe.

def load_csv():
    mainDf = pd.read_csv('GTD_Data_Frame_Without_Duplicates.csv')
    firstCrawlDf = pd.read_csv('lahavs_first_crawl.csv')
    secondCrawlDf = pd.read_csv('lahavs_second_crawl.csv')
    thirdCrawlDf = pd.read_csv('shellys_first_crawl.csv')
    fourthCrawlDf = pd.read_csv('shellys_second_crawl.csv')
    lastCrawlDf = pd.read_csv('last_crawl.csv')
    return mainDf,firstCrawlDf,secondCrawlDf,thirdCrawlDf,fourthCrawlDf,lastCrawlDf

In [212]:
#check data frame
mainDf,firstCrawlDf,secondCrawlDf,thirdCrawlDf,fourthCrawlDf,lastCrawlDf=load_csv()
lastCrawlDf.head()

,Unnamed: 0,attackTypeList,successfulAttackList,hostagesList,ransomList,propertyDamageList,suicideAttackList,partOfMultipleIncidentList,typeOfWeaponList,subTypeOfWeaponList
0,0,Bombing/Explosion,No,No,No,Yes,No,No,Explosives,Unknown Explosive Type
1,1,Hijacking,No,Yes,No,No,No,No,Unknown,Unknown
2,2,Assassination,Yes,No,No,No,No,No,Firearms,Unknown Gun Type
3,3,Assassination,Yes,No,No,No,No,No,Firearms,Rifle/Shotgun (non-automatic)
4,4,Hostage Taking (Kidnapping),Yes,Yes,No,No,No,No,Unknown,Unknown

In [213]:
def unionDf():
    mainDf,firstCrawlDf,secondCrawlDf,thirdCrawlDf,fourthCrawlDf,lastCrawlDf=load_csv()
    #adding attackType
    attackTypeList=firstCrawlDf.attackTypeList.tolist()
    attackTypeList.extend(secondCrawlDf.attackTypeList.tolist())
    attackTypeList.extend(thirdCrawlDf.attackTypeList.tolist())
    attackTypeList.extend(fourthCrawlDf.attackTypeList.tolist())
    attackTypeList.extend(lastCrawlDf.attackTypeList.tolist())
    #adding successfulAttack
    successfulAttackList=firstCrawlDf.successfulAttackList.tolist()
    successfulAttackList.extend(secondCrawlDf.successfulAttackList.tolist())
    successfulAttackList.extend(thirdCrawlDf.successfulAttackList.tolist())
    successfulAttackList.extend(fourthCrawlDf.successfulAttackList.tolist())
    successfulAttackList.extend(lastCrawlDf.successfulAttackList.tolist())
    #adding hostagesList
    hostagesList=firstCrawlDf.hostagesList.tolist()
    hostagesList.extend(secondCrawlDf.hostagesList.tolist())
    hostagesList.extend(thirdCrawlDf.hostagesList.tolist())
    hostagesList.extend(fourthCrawlDf.hostagesList.tolist())
    hostagesList.extend(lastCrawlDf.hostagesList.tolist())
    #adding ransomList
    ransomList=firstCrawlDf.ransomList.tolist()
    ransomList.extend(secondCrawlDf.ransomList.tolist())
    ransomList.extend(thirdCrawlDf.ransomList.tolist())
    ransomList.extend(fourthCrawlDf.ransomList.tolist())
    ransomList.extend(lastCrawlDf.ransomList.tolist())
    #adding propertyDamageList
    propertyDamageList=firstCrawlDf.propertyDamageList.tolist()
    propertyDamageList.extend(secondCrawlDf.propertyDamageList.tolist())
    propertyDamageList.extend(thirdCrawlDf.propertyDamageList.tolist())
    propertyDamageList.extend(fourthCrawlDf.propertyDamageList.tolist())
    propertyDamageList.extend(lastCrawlDf.propertyDamageList.tolist())
    #adding suicideAttackList
    suicideAttackList=firstCrawlDf.suicideAttackList.tolist()
    suicideAttackList.extend(secondCrawlDf.suicideAttackList.tolist())
    suicideAttackList.extend(thirdCrawlDf.suicideAttackList.tolist())
    suicideAttackList.extend(fourthCrawlDf.suicideAttackList.tolist())
    suicideAttackList.extend(lastCrawlDf.suicideAttackList.tolist())
    #adding partOfMultipleIncidentList
    partOfMultipleIncidentList=firstCrawlDf.partOfMultipleIncidentList.tolist()
    partOfMultipleIncidentList.extend(secondCrawlDf.partOfMultipleIncidentList.tolist())
    partOfMultipleIncidentList.extend(thirdCrawlDf.partOfMultipleIncidentList.tolist())
    partOfMultipleIncidentList.extend(fourthCrawlDf.partOfMultipleIncidentList.tolist())
    partOfMultipleIncidentList.extend(lastCrawlDf.partOfMultipleIncidentList.tolist())
    #adding typeOfWeaponList
    typeOfWeaponList=firstCrawlDf.typeOfWeaponList.tolist()
    typeOfWeaponList.extend(secondCrawlDf.typeOfWeaponList.tolist())
    typeOfWeaponList.extend(thirdCrawlDf.typeOfWeaponList.tolist())
    typeOfWeaponList.extend(fourthCrawlDf.typeOfWeaponList.tolist())
    typeOfWeaponList.extend(lastCrawlDf.typeOfWeaponList.tolist())
    #adding subTypeOfWeaponList
    subTypeOfWeaponList=firstCrawlDf.subTypeOfWeaponList.tolist()
    subTypeOfWeaponList.extend(secondCrawlDf.subTypeOfWeaponList.tolist())
    subTypeOfWeaponList.extend(thirdCrawlDf.subTypeOfWeaponList.tolist())
    subTypeOfWeaponList.extend(fourthCrawlDf.subTypeOfWeaponList.tolist())
    subTypeOfWeaponList.extend(lastCrawlDf.subTypeOfWeaponList.tolist())
    #merge into the main df
    mainDf['attack_Type'.upper()]=attackTypeList
    mainDf['Successful_Attack'.upper()]=successfulAttackList
    mainDf['hostages'.upper()]=hostagesList
    mainDf['ransom'.upper()]=ransomList
    mainDf['property_Damage'.upper()]=propertyDamageList
    mainDf['suicide_Attack'.upper()]=suicideAttackList
    mainDf['part_Of_Multiple_Incident'.upper()]=partOfMultipleIncidentList
    mainDf['type_Of_Weapon_List'.upper()]=typeOfWeaponList
    mainDf['sub_Type_Of_Weapon'.upper()]=subTypeOfWeaponList
    
    return mainDf

In [214]:
#merging the data frames and saving to a csv
df=unionDf()
df=df.drop(columns="Unnamed: 0")
df.to_csv('df_merged.csv')

In [217]:
df

,GTD_ID,DATE,COUNTRY,CITY,PERPETRATOR_GROUP,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON
0,201912310033,2019-12-31,China,Hong Kong,Unknown,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb
1,201912310032,2019-12-31,India,Bagiot Dora,Unknown,0,1,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Land Mine
2,201912310031,2019-12-31,Sudan,El Geneina,Unknown,2,0,"Government (General),Police",Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type
3,201912310030,2019-12-31,Sudan,El Geneina,Unknown,2,1,Police,Unknown,Yes,No,No,Yes,No,No,Unknown,Unknown
4,201912310028,2019-12-31,Iraq,Baghdad,Unknown,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201178,197001000003,1970-01-00,Japan,Fukouka,Unknown,Unknown,Unknown,Government (Diplomatic),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Unknown
201179,197001000002,1970-01-00,Greece,Athens,Unknown,Unknown,Unknown,Government (Diplomatic),Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type
201180,197001000001,1970-01-00,Philippines,Unknown,Unknown,1,0,Journalists & Media,Assassination,Yes,No,No,No,No,No,Unknown,Unknown
201181,197000000002,1970-00-00,Mexico,Mexico city,23rd of September Communist League,0,0,Government (Diplomatic),Hostage Taking (Kidnapping),Yes,Yes,Yes,No,No,No,Unknown,Unknown
201182,197000000001,1970-07-02,Dominican Republic,Santo Domingo,MANO-D,1,0,Private Citizens & Property,Assassination,Yes,No,No,No,No,No,Unknown,Unknown

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201183 entries, 0 to 201182
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   GTD_ID                     201183 non-null  int64
 1   DATE                       201183 non-null  object
 2   COUNTRY                    201183 non-null  object
 3   CITY                       200757 non-null  object
 4   PERPETRATOR_GROUP          201179 non-null  object
 5   FATALITIES                 201183 non-null  object
 6   INJURED                    201183 non-null  object
 7   TARGET_TYPE                201183 non-null  object
 8   ATTACK_TYPE                201183 non-null  object
 9   SUCCESSFUL_ATTACK          201183 non-null  object
 10  HOSTAGES                   201183 non-null  object
 11  RANSOM                     201183 non-null  object
 12  PROPERTY_DAMAGE            201183 non-null  object
 13  SUICIDE_ATTACK             201183 non-null  object
 14  PART_OF_MULTIPLE_INCIDENT  201183 non-null  object
 15  TYPE_OF_WEAPON_LIST        201183 non-null  object
 16  SUB_TYPE_OF_WEAPON         201183 non-null  object
dtypes: int64(1), object(16)
memory usage: 26.1+ MB

In [220]:
df.dropna(axis=0,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200753 entries, 0 to 201182
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   GTD_ID                     200753 non-null  int64
 1   DATE                       200753 non-null  object
 2   COUNTRY                    200753 non-null  object
 3   CITY                       200753 non-null  object
 4   PERPETRATOR_GROUP          200753 non-null  object
 5   FATALITIES                 200753 non-null  object
 6   INJURED                    200753 non-null  object
 7   TARGET_TYPE                200753 non-null  object
 8   ATTACK_TYPE                200753 non-null  object
 9   SUCCESSFUL_ATTACK          200753 non-null  object
 10  HOSTAGES                   200753 non-null  object
 11  RANSOM                     200753 non-null  object
 12  PROPERTY_DAMAGE            200753 non-null  object
 13  SUICIDE_ATTACK             200753 non-null  object
 14  PART_OF_MULTIPLE_INCIDENT  200753 non-null  object
 15  TYPE_OF_WEAPON_LIST        200753 non-null  object
 16  SUB_TYPE_OF_WEAPON         200753 non-null  object
dtypes: int64(1), object(16)
memory usage: 27.6+ MB

In [221]:
dfCopy=df.copy()
dfCopy=dfCopy.replace({'Unknown': np.nan})

In [222]:
dfCopy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200753 entries, 0 to 201182
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   GTD_ID                     200753 non-null  int64
 1   DATE                       200753 non-null  object
 2   COUNTRY                    200753 non-null  object
 3   CITY                       190032 non-null  object
 4   PERPETRATOR_GROUP          111980 non-null  object
 5   FATALITIES                 188803 non-null  object
 6   INJURED                    181830 non-null  object
 7   TARGET_TYPE                193953 non-null  object
 8   ATTACK_TYPE                191049 non-null  object
 9   SUCCESSFUL_ATTACK          200614 non-null  object
 10  HOSTAGES                   200122 non-null  object
 11  RANSOM                     199065 non-null  object
 12  PROPERTY_DAMAGE            174231 non-null  object
 13  SUICIDE_ATTACK             200614 non-null  object
 14  PART_OF_MULTIPLE_INCIDENT  200614 non-null  object
 15  TYPE_OF_WEAPON_LIST        175965 non-null  object
 16  SUB_TYPE_OF_WEAPON         170294 non-null  object
dtypes: int64(1), object(16)
memory usage: 27.6+ MB

In [223]:
#checking the nan data
dfCheck=dfCopy.copy()
dfCheck=dfCheck.drop(columns='PERPETRATOR_GROUP')
dfCheck.dropna(axis=0,inplace=True)
dfCheck.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123692 entries, 0 to 201177
Data columns (total 16 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   GTD_ID                     123692 non-null  int64
 1   DATE                       123692 non-null  object
 2   COUNTRY                    123692 non-null  object
 3   CITY                       123692 non-null  object
 4   FATALITIES                 123692 non-null  object
 5   INJURED                    123692 non-null  object
 6   TARGET_TYPE                123692 non-null  object
 7   ATTACK_TYPE                123692 non-null  object
 8   SUCCESSFUL_ATTACK          123692 non-null  object
 9   HOSTAGES                   123692 non-null  object
 10  RANSOM                     123692 non-null  object
 11  PROPERTY_DAMAGE            123692 non-null  object
 12  SUICIDE_ATTACK             123692 non-null  object
 13  PART_OF_MULTIPLE_INCIDENT  123692 non-null  object
 14  TYPE_OF_WEAPON_LIST        123692 non-null  object
 15  SUB_TYPE_OF_WEAPON         123692 non-null  object
dtypes: int64(1), object(15)
memory usage: 16.0+ MB

In [98]:
#saving cleaned data frame without nan values  to csv
dfCheck.to_csv('df_cleaned.csv')

In [297]:
dfCheck

,GTD_ID,DATE,COUNTRY,CITY,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON
0,201912310033,2019-12-31,China,Hong Kong,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb
1,201912310032,2019-12-31,India,Bagiot Dora,0,1,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Land Mine
2,201912310031,2019-12-31,Sudan,El Geneina,2,0,"Government (General),Police",Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type
4,201912310028,2019-12-31,Iraq,Baghdad,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type
8,201912310024,2019-12-31,Philippines,Inug-ug,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Grenade
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201173,197001030001,1970-01-03,United States,Madison,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Gasoline or Alcohol
201174,197001020003,1970-01-02,United States,Madison,0,0,Military,Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb
201175,197001020002,1970-01-02,United States,Oakland,0,0,Utilities,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type
201176,197001020001,1970-01-02,Uruguay,Montevideo,0,0,Police,Assassination,No,No,No,No,No,No,Firearms,Automatic Weapon
201177,197001010002,1970-01-01,United States,Cairo,0,0,Police,Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type

In [298]:
#changing column DATE from Object type to numeric type
###there were alot of days with 00!!!!!!!!!!!
def change_date_format(df):
    #dayList=[]
    monthList=[]
    yearList= []

    for date in df.DATE:
        tempYear=date[0]+date[1]+date[2]+date[3]
        tempMonth=date[5]+date[6]
        #tempDay=date[8]+date[9]
        #dayList.append(tempDay)
        monthList.append(tempMonth)
        yearList.append(tempYear)
    df=df.drop(columns="DATE")
    df['month'.upper()]=monthList
    df['year'.upper()]=yearList
    df['MONTH'] = pd.to_numeric(df['MONTH'])
    df['YEAR'] = pd.to_numeric(df['YEAR'])
    return df

In [299]:
df=change_date_format(dfCheck)
df

,GTD_ID,COUNTRY,CITY,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON,MONTH,YEAR
0,201912310033,China,Hong Kong,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb,12,2019
1,201912310032,India,Bagiot Dora,0,1,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Land Mine,12,2019
2,201912310031,Sudan,El Geneina,2,0,"Government (General),Police",Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type,12,2019
4,201912310028,Iraq,Baghdad,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type,12,2019
8,201912310024,Philippines,Inug-ug,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Grenade,12,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201173,197001030001,United States,Madison,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Gasoline or Alcohol,1,1970
201174,197001020003,United States,Madison,0,0,Military,Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb,1,1970
201175,197001020002,United States,Oakland,0,0,Utilities,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type,1,1970
201176,197001020001,Uruguay,Montevideo,0,0,Police,Assassination,No,No,No,No,No,No,Firearms,Automatic Weapon,1,1970
201177,197001010002,United States,Cairo,0,0,Police,Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type,1,1970

In [300]:
#converting FATALITIES and INJURED from object type to numeric type
def convert_fatalities_and_injured_to_numeric(df):
    df['FATALITIES'] = pd.to_numeric(df['FATALITIES'])
    df['INJURED']=pd.to_numeric(df['INJURED'])
    return df

In [301]:
df = convert_fatalities_and_injured_to_numeric(df)
dfBackup = df.copy()
dfBackup

,GTD_ID,COUNTRY,CITY,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON,MONTH,YEAR
0,201912310033,China,Hong Kong,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb,12,2019
1,201912310032,India,Bagiot Dora,0,1,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Land Mine,12,2019
2,201912310031,Sudan,El Geneina,2,0,"Government (General),Police",Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type,12,2019
4,201912310028,Iraq,Baghdad,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type,12,2019
8,201912310024,Philippines,Inug-ug,0,0,Private Citizens & Property,Bombing/Explosion,Yes,No,No,No,No,No,Explosives,Grenade,12,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201173,197001030001,United States,Madison,0,0,Government (General),Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Gasoline or Alcohol,1,1970
201174,197001020003,United States,Madison,0,0,Military,Facility/Infrastructure Attack,Yes,No,No,Yes,No,No,Incendiary,Molotov Cocktail/Petrol Bomb,1,1970
201175,197001020002,United States,Oakland,0,0,Utilities,Bombing/Explosion,Yes,No,No,Yes,No,No,Explosives,Unknown Explosive Type,1,1970
201176,197001020001,Uruguay,Montevideo,0,0,Police,Assassination,No,No,No,No,No,No,Firearms,Automatic Weapon,1,1970
201177,197001010002,United States,Cairo,0,0,Police,Armed Assault,Yes,No,No,Yes,No,No,Firearms,Unknown Gun Type,1,1970

In [302]:
#adding new code columns for object columns
def add_code_columns(df):

    df['COUNTRY']=df['COUNTRY'].astype('category')
    values_country = df['COUNTRY'].tolist()
    list_country = df['COUNTRY'].cat.codes
    dict_country = dict(zip(list_country,values_country))
    df['COUNTRY'] = list_country
    
    df['CITY']=df['CITY'].astype('category')  
    values_city = df['CITY'].tolist()
    list_city = df['CITY'].cat.codes
    dict_city = dict(zip(list_city,values_city))
    df['CITY'] = list_city
    
    df['TARGET_TYPE']=df['TARGET_TYPE'].astype('category')
    values_target_type = df['TARGET_TYPE'].tolist()
    list_target_type = df['TARGET_TYPE'].cat.codes
    dict_target_type = dict(zip(list_target_type,values_target_type))
    df['TARGET_TYPE']=list_target_type
    
    df['ATTACK_TYPE']=df['ATTACK_TYPE'].astype('category')
    values_attack_type = df['ATTACK_TYPE'].tolist()
    list_attack_type = df['ATTACK_TYPE'].cat.codes
    dict_attack_type = dict(zip(list_attack_type,values_attack_type))
    df['ATTACK_TYPE']= list_attack_type
    
    df['SUCCESSFUL_ATTACK']=df['SUCCESSFUL_ATTACK'].astype('category')
    values_successful_attack = df['SUCCESSFUL_ATTACK'].tolist()
    list_successful_attack = df['SUCCESSFUL_ATTACK'].cat.codes
    dict_successful_attack = dict(zip(list_successful_attack,values_successful_attack))
    df['SUCCESSFUL_ATTACK']= list_successful_attack
    
    df['HOSTAGES']=df['HOSTAGES'].astype('category')
    values_hostages = df['HOSTAGES'].tolist()
    list_hostages = df['HOSTAGES'].cat.codes
    dict_hostages = dict(zip(list_hostages,values_hostages))
    df['HOSTAGES']=list_hostages
        
    df['RANSOM']=df['RANSOM'].astype('category')
    values_ransom = df['RANSOM'].tolist()
    list_ransom = df['RANSOM'].cat.codes
    dict_ransom = dict(zip(list_ransom,values_ransom))
    df['RANSOM']=list_ransom
    
    df['PROPERTY_DAMAGE']=df['PROPERTY_DAMAGE'].astype('category')
    values_property_damage = df['PROPERTY_DAMAGE'].tolist()
    list_property_damage = df['PROPERTY_DAMAGE'].cat.codes
    dict_property_damage = dict(zip(list_property_damage,values_property_damage))
    df['PROPERTY_DAMAGE']=list_property_damage
    
    df['SUICIDE_ATTACK']=df['SUICIDE_ATTACK'].astype('category')
    values_suicide_attack = df['SUICIDE_ATTACK'].tolist()
    list_suicide_attack = df['SUICIDE_ATTACK'].cat.codes
    dict_suicide_attack = dict(zip(list_suicide_attack,values_suicide_attack))
    df['SUICIDE_ATTACK']=list_suicide_attack
    
    df['PART_OF_MULTIPLE_INCIDENT']=df['PART_OF_MULTIPLE_INCIDENT'].astype('category')
    values_part_of_multiple_incident = df['PART_OF_MULTIPLE_INCIDENT'].tolist()
    list_part_of_multiple_incident = df['PART_OF_MULTIPLE_INCIDENT'].cat.codes
    dict_part_of_multiple_incident = dict(zip(list_part_of_multiple_incident,values_part_of_multiple_incident))
    df['PART_OF_MULTIPLE_INCIDENT']=list_part_of_multiple_incident 
    
    df['TYPE_OF_WEAPON_LIST']=df['TYPE_OF_WEAPON_LIST'].astype('category')
    values_type_of_weapon_list = df['TYPE_OF_WEAPON_LIST'].tolist()
    list_type_of_weapon_list = df['TYPE_OF_WEAPON_LIST'].cat.codes
    dict_type_of_weapon_list = dict(zip(list_type_of_weapon_list,values_type_of_weapon_list))
    df['TYPE_OF_WEAPON_LIST']=list_type_of_weapon_list
    
    df['SUB_TYPE_OF_WEAPON']=df['SUB_TYPE_OF_WEAPON'].astype('category')
    values_sub_type_of_weapon = df['SUB_TYPE_OF_WEAPON'].tolist()
    list_sub_type_of_weapon = df['SUB_TYPE_OF_WEAPON'].cat.codes
    dict_sub_type_of_weapon = dict(zip(list_sub_type_of_weapon,values_sub_type_of_weapon))
    df['SUB_TYPE_OF_WEAPON']=list_sub_type_of_weapon
       
    return df,dict_country,dict_city,dict_target_type,dict_attack_type,dict_successful_attack,dict_hostages,dict_ransom,dict_property_damage,dict_suicide_attack,dict_part_of_multiple_incident,dict_type_of_weapon_list,dict_sub_type_of_weapon

In [303]:
df,dict_country,dict_city,dict_target_type,dict_attack_type,dict_successful_attack,dict_hostages,dict_ransom,dict_property_damage,dict_suicide_attack,dict_part_of_multiple_incident,dict_type_of_weapon_list,dict_sub_type_of_weapon = add_code_columns(df)

In [307]:
df

,GTD_ID,COUNTRY,CITY,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON,MONTH,YEAR
0,201912310033,32,11429,0,0,143,3,1,0,0,1,0,0,3,12,12,2019
1,201912310032,76,2512,0,1,379,2,1,0,0,0,0,0,1,10,12,2019
2,201912310031,166,8676,2,0,182,0,1,0,0,1,0,0,2,27,12,2019
4,201912310028,80,2501,0,0,379,2,1,0,0,1,0,0,1,26,12,2019
8,201912310024,136,11964,0,0,379,2,1,0,0,0,0,0,1,6,12,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201173,197001030001,185,16952,0,0,143,3,1,0,0,1,0,0,3,5,1,1970
201174,197001020003,185,16952,0,0,234,3,1,0,0,1,0,0,3,12,1,1970
201175,197001020002,185,20601,0,0,545,2,1,0,0,1,0,0,1,26,1,1970
201176,197001020001,186,18909,0,0,317,1,0,0,0,0,0,0,2,1,1,1970
201177,197001010002,185,5313,0,0,317,0,1,0,0,1,0,0,2,27,1,1970

In [310]:
dict_city.get(5313)

'Cairo'

,GTD_ID,COUNTRY,CITY,FATALITIES,INJURED,TARGET_TYPE,ATTACK_TYPE,SUCCESSFUL_ATTACK,HOSTAGES,RANSOM,PROPERTY_DAMAGE,SUICIDE_ATTACK,PART_OF_MULTIPLE_INCIDENT,TYPE_OF_WEAPON_LIST,SUB_TYPE_OF_WEAPON,MONTH,YEAR
0,123691,32,11429,0,0,143,3,1,0,0,1,0,0,3,12,12,48
1,123690,76,2512,0,1,379,2,1,0,0,0,0,0,1,10,12,48
2,123689,166,8676,2,0,182,0,1,0,0,1,0,0,2,27,12,48
4,123688,80,2501,0,0,379,2,1,0,0,1,0,0,1,26,12,48
8,123687,136,11964,0,0,379,2,1,0,0,0,0,0,1,6,12,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201173,4,185,16952,0,0,143,3,1,0,0,1,0,0,3,5,1,0
201174,3,185,16952,0,0,234,3,1,0,0,1,0,0,3,12,1,0
201175,2,185,20601,0,0,545,2,1,0,0,1,0,0,1,26,1,0
201176,1,186,18909,0,0,317,1,0,0,0,0,0,0,2,1,1,0
201177,0,185,5313,0,0,317,0,1,0,0,1,0,0,2,27,1,0